$.jStorage.set('language', {
	it : {
		restart : 'riavvia',
		generateInverse : 'calcola relazioni inverse',
		autoExpand : 'espandi automaticamente le relazioni',
		autoSameAs : 'calcola relazioni inverse di tipo sameAs',
		autoCollectImages : 'raccogli le immagini durante la navigazione',
		autoDrawMap : 'geolocalizza le risorse',
		noName : 'denominazione non trovata',
		addUri : 'inserisci una uri',
		findResource : 'cerca una risorsa',
		choose : 'scegli...',
		resourceMissing : 'risorsa non trovata',
		resourceMissingDoc : 'non sono state trovate proprietà di tipo literal per la risorsa per la lingua impostata o la risorsa non è momentaneamente disponibile nell\'endpoint',
		options : 'OPZIONI',
		endpointNotConfigured : 'nessun endpoint configurato per la risorsa',
		endpointNotConfiguredSoInternal : 'nessun endpoint configurato per la risorsa, generazione grafo temporaneo',
		impostaUnaURI : 'imposta un uri, esegui una ricerca \no scegli tra gli esempi proposti',
		example : 'esempio',
		noIe : 'Siamo spiacenti ma attualmente Internet Explorer non &egrave; totalmente supportato.',
		enpointNotAvailable : 'errore: endpoint non disponibile',
		enpointNotAvailableOrSLow : 'errore: endpoint non disponibile o richiesta scaduta',
		imagesNotFound : 'nessuna immagine per le risorse aperte',
		mapNotFound : 'nessuna mappa per le riorse aperte',
		propsNotFound : 'nessuna propriet&agrave; trovata',
		propsFound : 'propriet&agrave; trovate',
		showResource : 'evidenza la risorsa',
		zoomIn : 'ingrandisci',
		showConsole : 'mostra la console delle ricerche (sperimentale)',
		executeThisQuery : 'esegui la query SPARQL in una nuova finestra',
		moreInfoOnThis : 'maggiori informazioni su questa risorsa',
		simpleSearch : 'ricerca semplice',
		simpleSearchDescription : 'DBpedia.org e Freebase consentono di interrogare le proprie risorse per parola chiave.<br /><br />Scegliendo un dataset e digitando almeno tre lettere di una parola chiave è possibile trovare gli URI delle risorse che si vuole esplorare.',
		insertUri : 'inserisci un URI',
		insertUriDescription : 'LodLive è in grado di analizzare e rappresentare risorse RDF anche se non supportate da un EndPoint per l\'accesso SPARQL.<br /><br />Inserendo un qualsiasi URI ad una risorsa RDF è possibile esplorarne contenuti e relazioni.',
		insertData : 'esplora i tuoi dati',
		liveLodLive : 'Scegliendo un endpoint tra quelli configurati è possibile navigare la risorsa e ricavare, attraverso delle query SPARQL preimpostate, non solo le proprietà dirette, ma anche tutte le proprietà inverse indipendentemente dal dataset di appartenenza.',
		centerClose : 'centra e chiudi le altre risorse',
		openOnline : 'visualizza la risorsa online',
		openRelated : 'espandi tutte le relazioni',
		removeResource : 'rimuovi questo box',
		noImage:'immagine non disponibile',
		connectedResources:'risorse collegate',
		tools: 'strumenti',
		vaInformation: 'visualizza informazioni aggiuntive',
		cCircle: 'cerchio vicino',
		foCircle: 'focus on circle',
		orURI: "apri l'URI della risorsa",
		eavRelations: "espandi tutte le relazioni visibili",
		dRelation: "relazione diretta",
		godRelations: 'gruppo di relazioni dirette',
		iRelation: "relazione inversa",
		goiRelations: 'gruppo di relazioni inverse',
		owlsRelation: 'owl:sameAs relazione',
		about: 'Circa',
		vRDF: "Visualizza RDF",
		contact: "Contatto",
		language: "Lingua",
		welcome: "Benvenuto a GraphView",
		intro: "Visualizza le informazioni di diversi domini di dati attraverso la grafica",
		aboutText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.",
		contactText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam."
	},
	en : {
		restart : 'restart',
		generateInverse : 'generate inverse relations',
		autoExpand : 'auto-expand mode',
		autoSameAs : 'generate inverse sameAs relations',
		autoCollectImages : 'collect images during browsing',
		autoDrawMap : 'geolocalize resources',
		noName : 'no title provided',
		addUri : 'insert an URI',
		findResource : 'find resources',
		choose : 'choose...',
		resourceMissing : 'resource not found',
		resourceMissingDoc : 'literal values not found or the resource is missing or not available in the endpoint',
		options : 'OPTIONS',
		endpointNotConfigured : 'no endpoint configured for the resource',
		endpointNotConfiguredSoInternal : 'no endpoint configured for the resource, generating temporary graph',
		impostaUnaURI : 'insert an uri, make a query or choose one of the examples provided',
		example : 'example',
		noIe : 'Sorry but Internet Explorer is not totally supported.',
		enpointNotAvailable : 'error: endpoint not available',
		enpointNotAvailableOrSLow : 'error: endpoint not available or the request timed out',
		imagesNotFound : 'no images for the opened resources',
		mapNotFound : 'no maps for the opened resources',
		propsNotFound : 'nothing found',
		propsFound : 'properties found',
		showResource : 'highlight the resource',
		zoomIn : 'zoom in',
		showConsole : 'show console (experimental)',
		executeThisQuery : 'execute the SPARQL query in a new window',
		moreInfoOnThis : 'more info on this resource',
		simpleSearch : 'simple search',
		simpleSearchDescription : 'DBpedia.org and Freebase allow  their resources to be queried through keywords.<br/><br/>You will be able to find the URIs of the resources  you want to explore by choosing a dataset and typing at least three letters of a keyword for it.',
		insertUri : 'insert URI',
		insertUriDescription : 'LodLive is able to analyse and "show"  RDF resources even when they are  not supported by a SPARQL access EndPoint.<br/><br/>By entering any URI to an RDF resource,  you will be able to explore contents and relationships.',
		insertData : 'browse your data',
		centerClose : 'focus on the resource',
		openOnline : 'access the online resource',
		openRelated : 'expand related resources',
		removeResource : 'remove this box',
		noImage:'image not available',
		connectedResources:'connected resources',
		tools:'tools',
		vaInformation: 'view additional information',
		cCircle: 'close circle',
		foCircle: 'focus on circle',
		orURI: 'open resource URI',
		eavRelations: 'expand all visible relations',
		dRelation: 'direct relation',
		godRelations: 'group of direct relations',
		iRelation: 'inverse relation',
		goiRelations: 'group of inverse relations',
		owlsRelation: 'owl:sameAs relation',
		about: 'About',
		vRDF: "Visualize RDF",
		contact: "Contact",
		language: "Language",
		welcome: "Welcome to GraphView",
		intro: "Visualize information from several data domains through graphs",
		aboutText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.",
		contactText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam."
	},
	pt : {
		restart : 'recomeçar',
		generateInverse : 'gerar relações inversas',
		autoExpand : 'modo auto-expandido',
		autoSameAs : 'gerar relações inversas sameAs',
		autoCollectImages : 'recolher imagens durante navegação',
		autoDrawMap : 'recursos geolocalizados',
		noName : 'título não fornecido',
		addUri : 'inserir um URI',
		findResource : 'encontrar recursos',
		choose : 'escolher...',
		resourceMissing : 'recurso não encontrado',
		resourceMissingDoc : 'valores literais não encontrados ou o recurso está em falta ou não está disponível no no endpoint',
		options : 'OPÇÕES',
		endpointNotConfigured : 'nenhum endpoint configurado para o recurso',
		endpointNotConfiguredSoInternal : 'nenhum endpoint configurado para o recurso, a gerar gráfico temporário',
		impostaUnaURI : 'inserir um uri, fazer um query ou escolher um dos exemplos fornecidos',
		example : 'exemplo',
		noIe : 'Desculpe mas o Internet Explorer não é totalmente suportado.',
		enpointNotAvailable : 'erro: endpoint não disponível',
		enpointNotAvailableOrSLow : 'erro: endpoint não disponível ou o pedido esgotou o tempo',
		imagesNotFound : 'sem imagens para o recurso aberto',
		mapNotFound : 'sem mapas para o recurso aberto',
		propsNotFound : 'nada encontrado',
		propsFound : 'foram encontradas propriedades',
		showResource : 'destacar o recurso',
		zoomIn : 'ampliar',
		showConsole : 'ver consola (experimental)',
		executeThisQuery : 'executar a query SPARQL numa nova janela',
		moreInfoOnThis : 'mais informações sobre este recurso',
		simpleSearch : 'pesquisa simples',
		simpleSearchDescription : 'DBpedia.org e Freebase permitem que os seus recursos sejam pesquisados através de palavras chaves.<br/><br/>Poderá encontrar os URIs dos recursos que deseja explorar por escolher um dataset e escrever pelo menos três letras de uma palavra chave a pesquisar.',
		insertUri : 'inserir um URI',
		insertUriDescription : 'LodLive consegue analizar e "apresentar" recursos RDF mesmo quando eles não são suportados por um EndPoint pelo acesso SPARQL.<br/><br/>Por introduzir um URI para um recurso RDF, poderá explorar os conteúdos e relações entre eles.',
		insertData : 'listar os dados',
		centerClose : 'focalizar no recurso',
		openOnline : 'aceder ao recurso online',
		openRelated : 'expandir recursos relacionados',
		removeResource : 'remover esta caixa',
		noImage:'imagem não disponível',
		connectedResources:'recursos relacionados'
	},
	fr : {
		restart : 'redémarrer',
		generateInverse : 'générer les relations inverses',
		autoExpand : 'mode auto-expansion',
		autoSameAs : 'générer les relations inverses sameAs',
		autoCollectImages : 'récupération des images pendant la navigation',
		autoDrawMap : 'géolocaliser les ressources',
		noName : 'sans titre',
		addUri : 'insérer une URI',
		findResource : 'chercher ressources',
		choose : 'choisir...',
		resourceMissing : 'ressource inconnue',
		resourceMissingDoc : 'valeurs littérales inconnues ou ressource inconnue ou ressource inaccessible au point d\'accès',
		options : 'OPTIONS',
		endpointNotConfigured : 'aucun endpoint n\'est configuré pour cette ressource',
		endpointNotConfiguredSoInternal : 'aucun endpoint n\'est configuré pour la ressource , génération d\'un graphe temporaire',
		impostaUnaURI : 'saisir une URI, faire une recherche ou choisir un des exemples fournis',
		example : 'exemple',
		noIe : 'Désolé, Internet Explorer n\'est pas complètement supporté',
		enpointNotAvailable : 'erreur: point d\'accès non disponible',
		enpointNotAvailableOrSLow : 'erreur: point d\'accès non disponible ou délai dépassé',
		imagesNotFound : 'aucune image pour les ressources en cours',
		mapNotFound : 'aucune carte pour les ressources en cours',
		propsNotFound : 'aucun résultat',
		propsFound : 'propriétés trouvées',
		showResource : 'surligner la ressource',
		zoomIn : 'zoomer',
		showConsole : 'afficher la console (expérimental)',
		executeThisQuery : 'exécuter la requête SPARQL query dans une nouvelle fenêtre',
		moreInfoOnThis : 'plus d\'informations sur cette ressource',
		simpleSearch : 'simple recherche',
		simpleSearchDescription : 'DBpedia.org et Freebase autorise les recherches par mots-clés.<br/><br/>Vous pouvez trouver les URI des ressources que vous cherchez en choisissant un jeu de données et en tapant au moins trois lettres d\'un mot clé .',
		insertUri : 'insérer une URI',
		insertUriDescription : 'LodLive is capable d\'analyser et de montrer des ressources RDF, y compris quand elles ne sont pas supportées par un point d\'accès SPARQL<br/><br/>En entrant une URI vers une ressource RDF,  vous serez capable d\'explorer son contenu et ses relations.',
		insertData : 'parcourir vos données',
		centerClose : 'se recentrer sur cette ressource',
		openOnline : 'accéder à la ressource en ligne',
		openRelated : 'déployer toutes les ressources associées',
		removeResource : 'retirer cette entrée',
		noImage:'image indisponible',
		connectedResources:'ressources reliées',
		tools: 'outils',
		vaInformation: 'afficher des informations supplémentaires',
		cCircle: 'cercle étroit',
		foCircle: 'focus on circle',
		orURI: 'URI de ressource ouverte',
		eavRelations: 'élargir toutes les relations visibles',
		dRelation: 'relation directe',
		godRelations: 'groupe de relations directes',
		iRelation: 'relation inverse',
		goiRelations: 'groupe de relations inverses',
		owlsRelation: 'owl:sameAs relation',
		about: 'À propos de',
		vRDF: "Visualiser RDF",
		contact: "Contact",
		language: "Langage",
		welcome: "Bienvenue à GraphView",
		intro: "Visualiser les informations de plusieurs domaines de données via des graphiques",
		aboutText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.",
		contactText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam."
	},
	gl : {
		restart : 'volver ao inicio',
		generateInverse : 'xerar as relacións inversas',
		autoExpand : 'modo autoexpansión',
		autoSameAs : 'xerar relacións sameAs inversas',
		autoCollectImages : 'recuperación das imaxes durante a navegación',
		autoDrawMap : 'xeolocalización dos recursos',
		noName : 'sen título',
		addUri : 'insira unha URI',
		findResource : 'buscar recursos',
		choose : 'seleccione...',
		resourceMissing : 'non se atopou o recurso',
		resourceMissingDoc : 'non se atoparon valores literais ou a busca non está dispoñíbel no punto de acceso neste momento',
		options : 'OPCIÓNS',
		endpointNotConfigured : 'non hai ningún punto de acceso configurado para o recurso',
		endpointNotConfiguredSoInternal : 'non hai ningún punto de acceso configurado para o recurso, xerando un grafo temporal',
		impostaUnaURI : 'insira unha uri, faga unha consulta ou escolla unha de entre os exemplos que se ofrecen',
		example : 'exemplo',
		noIe : 'Desafortunadamente o soporte para Internet Explorer non está totalmente finalizado.',
		enpointNotAvailable : 'erro: punto de acceso non dispoñíbel',
		enpointNotAvailableOrSLow : 'erro: punto de acceso non dispoñíbel ou a consulta demorou demasiado',
		imagesNotFound : 'non hai imaxes para os recursos abertos',
		mapNotFound : 'non hai mapas para os recursos abertos',
		propsNotFound : 'non se atoparon propiedades',
		propsFound : 'atopáronse propiedades',
		showResource : 'destacar o recurso',
		zoomIn : 'ampliar',
		showConsole : 'amosar a consola (experimental)',
		executeThisQuery : 'executar a consulta SPARQL nunha nova xanela',
		moreInfoOnThis : 'máis información sobre este recurso',
		simpleSearch : 'busca simple',
		simpleSearchDescription : 'DBpedia.org e Freebase permiten a busca mediante palabras chave.<br/><br/>Pode atopar a URI do recurso que desexe explorar seleccionando un conxunto de datos e escribindo, cando menos, as tres primeiras letras dunha palabra chave.',
		insertUri : 'insira unha URI',
		insertUriDescription : 'LodLive é capaz de analizar e amosar recursos RDF mesmo sen o soporte dun punto de acceso SPARQL.<br/><br/>Introducindo unha URI a un recurso RDF, poderá explorar contidos e relacións.',
		insertData : 'explore os seus datos',
		centerClose : 'centrar este recurso e pechar os demais',
		openOnline : 'acceder ao recurso en liña',
		openRelated : 'expandir todas as relacións',
		removeResource : 'eliminar este recurso',
		noImage:'imaxe non dispoñíbel',
		connectedResources:'recursos ligados'
	},
	es : {
		restart : 'reiniciar',
		generateInverse : 'generar relaciones inversas',
		autoExpand : 'modo de expansión automática',
		autoSameAs : 'generar relaciones inversas de sameAs',
		autoCollectImages : 'recolectar imágenes durante la navegación',
		autoDrawMap : 'geolocalizar recursos',
		noName : 'sin título proporcionado',
		addUri : 'insertar una URI',
		findResource : 'encontrar recursos',
		choose : 'elegir ...',
		resourceMissing : 'recurso no encontrado',
		resourceMissingDoc : 'no se encuentran los valores literales o el recurso falta o no está disponible en el endpoint',
		options : 'OPCIONES',
		endpointNotConfigured : 'no hay endpoint configurado para el recurso',
		endpointNotConfiguredSoInternal : 'no hay endpoint configurado para el recurso, generando un gráfico temporal',
		impostaUnaURI : 'inserta una uri, haz una consulta o elige uno de los ejemplos proporcionados',
		example : 'ejemplo',
		noIe : 'Lo siento, pero Internet Explorer no es totalmente compatible.',
		enpointNotAvailable : 'error: endpoint no disponible',
		enpointNotAvailableOrSLow : 'error: endpoint no está disponible o la solicitud ha caducado',
		imagesNotFound : 'no hay imágenes para los recursos abiertos',
		mapNotFound : 'no hay mapas para los recursos abiertos',
		propsNotFound : 'nada encontrado',
		propsFound : 'propiedades encontradas',
		showResource : 'resaltar el recurso',
		zoomIn : 'acercar',
		showConsole : 'mostrar consola (experimental)',
		executeThisQuery : 'ejecuta la consulta SPARQL en una nueva ventana',
		moreInfoOnThis : 'más información sobre este recurso',
		simpleSearch : 'búsqueda simple',
		simpleSearchDescription : 'DBpedia.org y Freebase permiten que sus recursos sean consultados mediante palabras clave. <br/> <br/> Podrás encontrar lss URI de los recursos que deseas explorar eligiendo un conjunto de datos y escribiendo al menos tres letras de una palabra clave para ello.',
		insertUri : 'insertar URI',
		insertUriDescription : 'LodLive puede analizar y "mostrar" recursos RDF incluso cuando no son compatibles con un EndPoint de acceso SPARQL. <br/> <br/> Al ingresar cualquier URI a un recurso RDF, podrá explorar los contenidos y relaciones.',
		insertData : 'explorar su data',
		centerClose : 'centrarse en el recurso',
		openOnline : 'acceder al recurso en línea',
		openRelated : 'expandir los recursos relacionados',
		removeResource : 'eliminar este cuadro',
		noImage:'imagen no disponible',
		connectedResources:'recursos conectados',
		tools:'herramientas',
		vaInformation: 'ver información adicional',
		cCircle: 'cerrar circulo',
		foCircle: 'centrarse en circulo',
		orURI: 'abrir recurso URI',
		eavRelations: 'expandir todas la relaciones visibles',
		dRelation: 'relación directa',
		godRelations: 'grupo de relaciones directas',
		iRelation: 'relación inversa',
		goiRelations: 'grupo de relaciones inversas',
		owlsRelation: 'relación owl:sameAs',
		about: 'Acerca de',
		vRDF: "Visualizar RDF",
		contact: "Contacto",
		language: "Idioma",
		welcome: "Bienvenido en GraphView",
		intro: "Visualiza información de varios dominios de datos a través de gráficos",
		aboutText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam.",
		contactText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero odio fugiat voluptatem dolor, provident officiis, id iusto! Obcaecati incidunt, qui nihil beatae magnam et repudiandae ipsa exercitationem, in, quo totam."
	}
});

//modified
// $.jStorage.set('selectedLanguage', 'en');
